# Generated by Django 4.0.1 on 2022-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_doggy_alter_news_options_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggy',
            name='poroda',
            field=models.CharField(default='', max_length=150, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='doggy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
