# Generated by Django 4.0.1 on 2022-01-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_doggy_category_doggy_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doggy',
            name='category_id',
        ),
        migrations.AddField(
            model_name='doggy',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория'),
        ),
    ]
